name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i -g corepack@latest && corepack enable

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Type check
        run: bun run test:types

      - name: Run tests
        run: bun run test
